version: '2'
services:
    zabbix-proxy-bfc:
        container_name: zabbix-proxy
        ports:
            - 10051:10051
        environment:
            - ZBX_HOSTNAME=CDA{DPT}-zproxy
            - ZBX_SERVER_HOST=zabbix.bfc.chambagri.fr
        image: zabbix/zabbix-proxy-sqlite3
